name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # The workflow contains a single job called "build"
  build:
    # The runner will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define the steps run in the workflow
    steps:
      # Checkout out the code in the repository
      # Checkout the submodule for the bibliography
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      # Compile LaTeX slides to PDF
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cs102-week-one.tex
      # Release a PDF of the slides
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cs102-week-one.pdf
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
